import express from "express";
import { register, login, getMe, logout, forgotPassword, resetPassword, updatePassword } from "../controllers/auth.js";
import { protect } from "../middlewares/auth.js";
import { loginLimiter } from "../middlewares/rateLimiter.js";
const router = express.Router();
router.post("/register", register);
router.post("/login", loginLimiter, login);
router.get("/me", protect, getMe);
router.post("/logout", logout);
router.post("/forgot-password", forgotPassword);
router.put('/reset-password/:resettoken', resetPassword);
router.put('/update-password', protect, updatePassword);
export default router;